# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.1/language-javascript/ for more details

version: 2.1

parameters:
  skip-interop-test:
    type: boolean
    default: false

executors:
  node:
    docker:
      - image: cimg/node:21.2.0-browsers
    resource_class: small
    working_directory: ~/repo
    environment:
      GIT_AUTHOR_EMAIL: visjsbot@gmail.com
      GIT_AUTHOR_NAME: vis-bot
      GIT_COMMITTER_EMAIL: visjsbot@gmail.com
      GIT_COMMITTER_NAME: vis-bot

  node-build:
    docker:
      - image: cimg/node:21.2.0-browsers
    resource_class: medium
    working_directory: ~/repo
    environment:
      GIT_AUTHOR_EMAIL: visjsbot@gmail.com
      GIT_AUTHOR_NAME: vis-bot
      GIT_COMMITTER_EMAIL: visjsbot@gmail.com
      GIT_COMMITTER_NAME: vis-bot

  node-interop:
    docker:
      - image: cimg/node:21.2.0-browsers
    resource_class: "medium+"
    working_directory: ~/repo
    environment:
      GIT_AUTHOR_EMAIL: visjsbot@gmail.com
      GIT_AUTHOR_NAME: vis-bot
      GIT_COMMITTER_EMAIL: visjsbot@gmail.com
      GIT_COMMITTER_NAME: vis-bot

jobs:
  prepare:
    executor: node

    steps:
      - checkout

      - run: npm ci

      - persist_to_workspace:
          root: .
          paths:
            - '*'

  build:
    executor: node-build

    steps:
      - attach_workspace:
          at: .

      - run: npm run build

      - persist_to_workspace:
          root: .
          paths:
            - 'declarations'
            - 'dist'
            - 'esnext'
            - 'peer'
            - 'standalone'

  lint:
    executor: node

    steps:
      - attach_workspace:
          at: .

      - run: npm run style
      - run: npm run lint

  type_check:
    executor: node

    steps:
      - attach_workspace:
          at: .

      - run: npm run type-check

  test_unit:
    executor: node

    steps:
      - attach_workspace:
          at: .

      - run: npm run test:coverage

  test_interop:
    executor: node-interop

    steps:
      - when:
          condition: << pipeline.parameters.skip-interop-test >>
          steps:
            - attach_workspace:
                at: .

            - run: npm pack

            - run:
                command: npm run test:interop -- --tmp-dir ../interop
                # This runs multiple things in parallel and only reports start
                # and end of individual commands, the full logs are printed at
                # the end. Due to this it's quite likely to go a long time
                # without any output and still finish successfully.
                no_output_timeout: 60m

            - store_artifacts:
                path: ../interop/repos/logs
                destination: interop-logs

      - unless:
          condition: << pipeline.parameters.skip-interop-test >>
          steps:
            - run: printf -- '%s\n' 'The interop test was skipped as per params.'

  release:
    executor: node-build

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Prepare NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN

      - run:
          name: Release
          command: |
            npx semantic-release

workflows:
  version: 2

  build:
    jobs:
      - prepare

      - build:
          requires:
            - prepare

      - lint:
          requires:
            - prepare

      - type_check:
          requires:
            - prepare

      - test_unit:
          requires:
            - prepare
            - build

      - test_interop:
          requires:
            - prepare
            - build

      - release:
          requires:
            - prepare
            - build
            - lint
            - type_check
            - test_unit
            - test_interop
          filters:
            branches:
              only:
                - master
